services:
  translator:
    build: ./translate
    image: model2_dabbdabbda:latest
    container_name: translator
    ports:
      - "8000:8000"
    restart: always

  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    ports:
      - "8080:8080"
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
    restart: always
