services:
  translator:
    build: ./translate
    container_name: translator
    ports:
      - "8000:8000"
    restart: "no"


  ocr:
    build: ./ocr
    container_name: ocr
    volumes:
      - ./ocr:/app
    ports:
      - "5000:5000"
    restart: "no"