services:
  translator:
    build: ./translate
    container_name: translator
    ports:
      - "8000:8000"
    restart: "no"

  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    ports:
      - "8080:8080"
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
    restart: "no"

  ocr:
    build: ./ocr
    container_name: ocr
    volumes:
      - .:/app
    working_dir: /app/ocr
    # The command to run will be specified at runtime
    command: python image_to_text.py
    restart: "no"