FROM python:3.9-slim

WORKDIR /app

# System dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        tesseract-ocr \
        tesseract-ocr-all \
        poppler-utils \
        libglib2.0-0 \
        libsm6 \
        libxrender1 \
        libxext6 \
        libgl1 && \
    rm -rf /var/lib/apt/lists/*

# Core Python packages
RUN pip install --no-cache-dir torch==2.2.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir pdf2image==1.16.3

# Requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -c "from doctr.models import ocr_predictor; ocr_predictor(pretrained=True)"

COPY ocr/ocr_engine.py .
COPY ocr/main_pipeline.py .
COPY ocr/layout_combined_enhanced.py .
COPY ocr/utils/file_utils.py .
COPY translate/app.py .
COPY translate/load_translation_model.py .

CMD ["python", "main_pipeline.py"]