FROM python:3.9

WORKDIR /app

# Install Tesseract OCR and OpenCV dependencies
RUN apt-get update && \
    apt-get install -y tesseract-ocr-all libglib2.0-0 libsm6 libxrender1 libxext6 libgl1 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
COPY requirements.txt .
RUN pip install --no-cache-dir ultralytics==8.0.203 --prefer-binary
RUN pip install --no-cache-dir torch==2.2.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir pdf2image

# Install poppler-utils for pdf2image PDF support
RUN apt-get update && apt-get install -y poppler-utils && rm -rf /var/lib/apt/lists/*

COPY image_to_text.py .

# Remove or comment out the tesseract_cmd line in your script for Docker use

CMD ["python", "image_to_text.py"]